require("config.paths")
require("config.plugins")
require("config.nvim-web-devicons")
-- require("config.material")
-- vim.cmd("colorscheme material") -- after theme and before statusline
require("config.statusline")
require("config.highlights")
require("config.lsp")
require("config.neoscroll")
require("config.telescope")
require("config.treesitter")
require("config.autopairs")
require("config.nvim-tree")
require("config.options")
require("config.harpoon")
require("config.indent-blankline")
require("config.formatter")
require("config.keymaps")
require("config.scrollbar")
require("config.neodim")
require("config.nvim_comment")
require("config.autocommands")
require("config.gitsigns")
